cart/urls.py
from django.urls import path

from .views import cart_detail_view, add_to_cart_view, remove_from_cart, clear_from_cart

app_name = 'cart'

urlpatterns = [
    path('', cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>', add_to_cart_view, name='cart_add'),
    path('remove/<int:product_id>', remove_from_cart, name='cart_remove'),
    path('clear/', clear_from_cart, name='cart_clear'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('pages.urls')),
                  path('Products/', include('products.urls')),
                  path('accounts/', include('allauth.urls')),
                  path('cart/', include('cart.urls')),
                  path('order/', include('orders.urls')),
                  path('payment/', include('payment.urls')),

                  # Roseta (i18n)
                  path('rosetta/', include('rosetta.urls'))
              ] \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/forms.py
from django import forms


class AddToCartProductForm(forms.Form):
    QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 51)]
    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.utils.translation import gettext as _

from products.models import Product
from .cart import Cart
from .form import AddToCartProductForm


def cart_detail_view(request):
    cart = Cart(request)

    for item in cart:
        item['product_update_quantity_form'] = AddToCartProductForm(initial=
        {
            'quantity': item['quantity'],
            'inplace': True,
        }
        )

    return render(request, 'cart/cart_detail.html',
                  {
                      'cart': cart,
                  })


@require_POST
def add_to_cart_view(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = AddToCartProductForm(request.POST)

    if form.is_valid():
        cleaned_data = form.cleaned_data
        quantity = cleaned_data['quantity']
        cart.add(product, quantity, replace_current_quantity=cleaned_data['inplace'])

    return redirect('Product')


def remove_from_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

    return redirect('cart:cart_detail')

def clear_from_cart(request):
    cart = Cart(request)
    if len(cart):
        cart.clear()
    else:
        messages.warning(request, _('Your cart is already empty'))
    return redirect('cart:cart_detail')

cart/templates/cart/cart_detail.html
{% extends '_base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load comment_tags %}
{% load rosetta %}
{% load persian_translation_tags %}
{% load humanize %}
{% load reduction_price %}

{% block page_title %}
    {% trans 'Cart detail' %}
{% endblock %}

{% block content %}
    <!-- Main Content Wrapper Start -->
    <div class="main-content-wrapper">
        <!-- Breadcrumb area Start -->
        {% trans 'cart' as name %}
        {% include 'top_header.html' with header_name=name %}
        <!-- Breadcrumb area End -->
        <div class="page-content-inner ptb--80">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mb-md--50">
                        <div class="row no-gutters">
                            <div class="col-12">
                                {% if cart %}
                                    <div class="table-content table-responsive">
                                        <table class="table text-center">
                                            <thead>
                                            <tr>
                                                <th>&nbsp;</th>
                                                <th>{% trans 'product picture' %}</th>
                                                <th>{% trans 'product name' %}</th>
                                                <th>{% trans 'product price' %}</th>
                                                <th>{% trans 'product quantity' %}</th>
                                                <th>{% trans 'Total' %}</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for item in cart %}
                                                <tr>
                                                    <td class="product-remove text-left">
                                                        <a href="{% url 'cart:cart_remove' item.product_obj.id %}">
                                                            <i class="flaticon flaticon-cross"></i>
                                                        </a></td>
                                                    <td class="product-thumbnail text-left">
                                                        {% if item.product_obj.image %}
                                                            <img class="m-auto" style="max-height: 400px;"
                                                                 src="{{ item.product_obj.image.url }}"
                                                                 alt="products">
                                                        {% else %}
                                                            <img class="m-auto" style="max-height: 400px;"
                                                                 src="{% static 'img/products/prod-10-70x88.jpg' %}"
                                                                 alt="products">
                                                        {% endif %}
                                                    </td>
                                                    <td class="product-name">
                                                        <h3>
                                                            <a href="{{ item.product_obj.get_absolute_url }}">
                                                                {{ item.product_obj.title }}
                                                            </a>
                                                        </h3>
                                                    </td>
                                                    <td class="product-price">
                                                        {% if not item.product_obj.reduction %}
                                                            <span class="product-price-wrapper">
                                                                <span class="money">{{ item.product_obj.price|intcomma:False|translate_numbers }} {% trans '$' %} </span>
                                                            </span>
                                                        {% else %}
                                                            <span class="product-price-wrapper">
                                                                <span class="money">{{ item.product_obj.price|price_reduction:item.product_obj.price_reduction|intcomma:False|translate_numbers }} {% trans '$' %} </span>
                                                            </span>
                                                        {% endif %}
                                                    </td>
                                                    <td class="product-quantity">
                                                        <form class="d-flex"
                                                              action="{% url 'cart:cart_add' item.product_obj.id %}"
                                                              method="post">
                                                            {% csrf_token %}
                                                            <div class="quantity">
                                                                <input type="number"
                                                                       class="quantity-input" name="quantity"
                                                                       id="qty-1" value="{{ item.quantity }}" min="1"
                                                                       max="20">
                                                            </div>
                                                            {{ item.product_update_quantity_form.inplace }}
                                                            <button class="xs success red-bg"
                                                                    type="submit">
                                                                <i class="fa fa-refresh"></i>
                                                            </button>
                                                        </form>
                                                    </td>
                                                    <td class="product-total-price">
                                                            <span class="product-price-wrapper">
                                                                <span class="money">{{ item.total_price|intcomma:False|translate_numbers }} {% trans '$' %} </span>
                                                            </span>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="row no-gutters border-top pt--20 mt--20">
                                        <div class="col-sm-6 text-sm-right">
                                            <a href="{% url 'cart:cart_clear' %}">
                                                <button type="submit"
                                                        class="cart-form__btn">{% trans 'clear cart' %}</button>
                                            </a>
                                        </div>
                                    </div>
                                {% else %}
                                    <a href="{% url 'Product' %}">{% trans 'Cart empty! Add some product to the car' %}</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% if cart %}
                        <div class="col-lg-4">
                            <div class="cart-collaterals">
                                <div class="cart-totals">
                                    <h5 class="font-size-14 font-bold mb--15">{% trans 'total' %}</h5>
                                    <div class="cart-calculator">
                                        <div class="cart-calculator__item order-total">
                                            <div class="cart-calculator__item--head">
                                                <span>{% trans 'total price' %}</span>
                                            </div>
                                            <div class="cart-calculator__item--value">
                                                <span class="product-price-wrapper">
                                                    <span class="money">{{ cart.get_total_price|intcomma:False|translate_numbers }} {% trans '$' %}</span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <a href="{% url 'order_create' %}"
                                   class="btn btn-fullwidth btn-bg-red btn-color-white btn-hover-2">
                                    {% trans 'Registration orders' %}
                                </a>
                            </div>
                        </div>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
    <!-- Main Content Wrapper Start -->

{% endblock %}

cart/templates/cart/cart_sidebar.html
{#{% extends '_base.html' %}#}
{% load i18n %}
{% load rosetta %}
{% load static %}
{% load persian_translation_tags %}
{% load reduction_price %}
{% load humanize %}

{% if cart %}
    <!-- Mini Cart Start -->
    <aside class="mini-cart" id="miniCart">
        <div class="mini-cart-wrapper">
            <a href="" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
            <div class="mini-cart-inner">
                <h3 class="mini-cart__heading mb--40 mb-lg--30 text-right">{% trans 'Cart' %}</h3>
                <div class="mini-cart__content">
                    <ul class="mini-cart__list text-right">
                        {% for item in cart %}
                            <li class="mini-cart__product d-flex justify-content-between">
                                <div class="mini-cart__product__image">
                                    <a href="{{ item.product_obj.get_absolute_url }}">
                                        {% if item.product_obj.image %}
                                            <img class="m-auto" style="max-height: 400px;"
                                                 src="{{ item.product_obj.image.url }}"
                                                 alt="products">
                                        {% else %}
                                            <img class="m-auto" style="max-height: 400px;"
                                                 src="{% static 'img/products/prod-1-100x100.jpg' %}" alt="products">
                                        {% endif %}
                                    </a>
                                </div>
                                <div class="mini-cart__product__content pt-2">
                                    <span class="mini-cart__product__title d-flex flex-row justify-content-between">
                                        <a href="{{ item.product_obj.get_absolute_url }}"> {{ item.product_obj.title }} </a>

                                        <a href="{% url 'cart:cart_remove' item.product_obj.id %}" class="">
                                            &#10060;
                                        </a>
                                    </span>
                                    {% if not item.product_obj.reduction %}
                                        <span class="mini-cart__product__quantity">
                                        <span>{{ item.product_obj.price|intcomma:False|translate_numbers }} {% trans '$' %}
                                        </span> &#215; <span>{{ item.quantity }}</span>
                                    </span>
                                    {% else %}
                                        <span class="mini-cart__product__quantity">
                                        <span>
                                            {{ item.product_obj.price|price_reduction:item.product_obj.price_reduction|intcomma:False|translate_numbers }} {% trans '$' %}
                                        </span> &#215; <span>{{ item.quantity }}
                                    </span>
                                    </span>
                                    {% endif %}
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                    <div class="mini-cart__total">
                        <span>{% trans 'total price' %}</span>
                        <span class="ammount">{{ cart.get_total_price|intcomma:False|translate_numbers }} {% trans '$' %}</span>
                    </div>
                    <div class="mini-cart__buttons">
                        <a href="{% url 'cart:cart_detail' %}"
                           class="btn btn-fullwidth btn-bg-sand mb--20">{% trans 'Go to cart' %}</a>
                        <a href="{% url 'order_create' %}"
                           class="btn btn-fullwidth btn-bg-sand">{% trans 'Checkout' %}</a>
                    </div>
                </div>
            </div>
        </div>
    </aside>
    <!-- Mini Cart End -->
{% endif %}